version: 2

project_name: hookspot

before:
  hooks:
    - go mod download

builds:
  - id: hookspot
    main: .
    binary: hookspot
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X hookspot/cmd.version={{ .Version }}
        -X hookspot/cmd.serverURL={{ .Env.SERVER_URL }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - hookspot
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Env.RELEASE_TAG }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
